### ISSUE TITLE
indent-blankline not working on blank lines

### ISSUE THREAD

**Issue by LollipopFt** [lukas-reineke/indent-blankline.nvim#227]
![image](https://user-images.githubusercontent.com/62802897/134608428-8e90ffdf-e663-4d07-94da-d1863af80ff9.png)
both config for indent-blankline on init.lua and problem (line 127 and 139) are in the same picture.

**Comment by lukas-reineke** [comment]
It looks like your `shiftwidth` is set to 8, but you use 4 space indentation.
Fixing that should fix the issue.

**Comment by lukas-reineke** [comment]
There was also a small issue that broke this specific case. I pushed a fix now.
But you should still update your `shiftwidth` to match your code.

**Comment by LollipopFt** [comment]
![image](https://user-images.githubusercontent.com/62802897/134629247-79035027-71d7-469e-9157-f23b8b0822ab.png)
um...
![image](https://user-images.githubusercontent.com/62802897/134629317-dde4aa34-8867-4024-a143-e2ca784a95a6.png)
the problem still seems to remain...

**Comment by lukas-reineke** [comment]
Run `:verbose set shiftwidth` (or `:verbose set tabstop` if you use tabs) in the file.
Looks like something is overwriting your settings.

**Comment by LollipopFt** [comment]
```
  shiftwidth=4
        Last set from Lua
  tabstop=4
        Last set from Lua
  softtabstop=4
        Last set from Lua
```
i seriously have no idea what could be causing this

**Comment by LollipopFt** [comment]
oh i think its just a problem with treesitter because the thing works on rust files but not on lua files.

**Comment by lukas-reineke** [comment]
I really can't see any other way this can happen except wrong `shiftwidth`

You can try to remove things from your config until it starts working.

**Comment by LollipopFt** [comment]
well i guess it's just my problem...

**Comment by leoflotor** [comment]
@LollipopFt , I don't think this was only your problem, I had it occurred to me last year but I gave up. Only now I noticed this thread and found a possible solution in the config file.

It has passed almost a year now form the question but I think that now it can be fixed by adding your configuration, or by adding the configuration as mentioned in the [docs](https://www.lunarvim.org/plugins/02-extra-plugins.html#indent-blankline), and by following a couple of indications mentioned in the configuration file `config.lua`:

```
-- After changing plugin config exit and reopen LunarVim, Run :PackerInstall :PackerCompile
```

I did it this way but the changes did not showed. I just exited **again** and reopened **again** LunarVim (Yeah... two times). Then my changes were visible.
