### ISSUE TITLE
Context Highlighting Problems

### ISSUE THREAD

**Issue by zacmar** [lukas-reineke/indent-blankline.nvim#80]
Context highlighting seems to have multiple problems. As an example, in `lua` it seems as if the highlighting breaks down if the cursor is in another node, that is a child of the node that "hosts" the indentation (at least I assume that that is the problem). Examples:
![2021-04-01-153131_830x438_scrot](https://user-images.githubusercontent.com/32982619/113301882-c71fd500-92ff-11eb-933d-0ffd807e8967.png)
![2021-04-01-153123_829x436_scrot](https://user-images.githubusercontent.com/32982619/113301885-c7b86b80-92ff-11eb-8e75-754fc1126c84.png)
![2021-04-01-153059_664x191_scrot](https://user-images.githubusercontent.com/32982619/113301887-c8510200-92ff-11eb-8d86-c5e0f946186a.png)
![2021-04-01-153052_659x189_scrot](https://user-images.githubusercontent.com/32982619/113301888-c8510200-92ff-11eb-94cc-4f9da15949bc.png)
![2021-04-01-153030_563x188_scrot](https://user-images.githubusercontent.com/32982619/113301890-c8e99880-92ff-11eb-9fe5-4fb34ab5090e.png)
![2021-04-01-153019_564x188_scrot](https://user-images.githubusercontent.com/32982619/113301891-c8e99880-92ff-11eb-9f6f-f1cb0a75c43d.png)
I would expect the highlighting to essentially be always active when my cursor is inside of the block (although for the last example, I _could_ possibly see how one may argue against that).

In `python` I also observe weird behavior. It is best described by pictures:
![2021-04-01-153735_421x292_scrot](https://user-images.githubusercontent.com/32982619/113302297-33023d80-9300-11eb-8e95-5524c1b2ce74.png)
![2021-04-01-153726_414x289_scrot](https://user-images.githubusercontent.com/32982619/113302303-339ad400-9300-11eb-906f-32ffd32a12a3.png)
![2021-04-01-153719_414x287_scrot](https://user-images.githubusercontent.com/32982619/113302306-339ad400-9300-11eb-9914-9bd5e62bc944.png)
![2021-04-01-153707_415x289_scrot](https://user-images.githubusercontent.com/32982619/113302308-34336a80-9300-11eb-8f95-7f831ec6341c.png)
![2021-04-01-153701_414x291_scrot](https://user-images.githubusercontent.com/32982619/113302312-34336a80-9300-11eb-9e2a-76769eab4347.png)
The problem here is that the `for`-indentation is highlighted even if the cursor is not inside the corresponding block, that it is not highlighted if the cursor is in the actually indented block, and that the highlighting is inconsistent between highlighting the line before `return` or not. I would prefer it to not highlight the last line. In fact, I would prefer it if there was not even and indent guide there at all.

Relevant configuration: 
```
vim.g.indent_blankline_use_treesitter = true
vim.g.indent_blankline_show_first_indent_level = false
vim.g.indent_blankline_show_trailing_blankline_indent = false
vim.g.indent_blankline_show_current_context = true
vim.g.indent_blankline_context_patterns = {'class', 'function', 'method', '^if', '^while', '^for', '^object', '^table', 'block', 'arguments'}
```

**Comment by lukas-reineke** [comment]
The first problem is like you already noticed, that the context is inside the `{}`, so it doesn't have any indentation.
I pushed a change now, it makes sense to only use a context that spans more than one line. That should fix some if your issues.

For the python one however, this all depends on what you set the context patterns to.
There is no logic to determine the context in this plugin at all. It all comes from treesitter. Any changes to that would need to be in the treesitter python grammar.

**Comment by zacmar** [comment]
> The first problem is like you already noticed, that the context is inside the `{}`, so it doesn't have any indentation.
> I pushed a change now, it makes sense to only use a context that spans more than one line. That should fix some if your issues.
> 

Makes sense! Im wondering if there are more elaborate ways to go about this, where `treesitter` is still responsible to give you the context, but then the plugin still checks where the corresponding indentation indentation in the file actually is. But the question is how much you gain from `treesitter` at all in this situation. For things like `if [1st indented block] else [2nd indented block] end` it may still be helpful I guess.

> For the python one however, this all depends on what you set the context patterns to.
> There is no logic to determine the context in this plugin at all. It all comes from treesitter. Any changes to that would need to be in the treesitter python grammar.

Okay, thanks for the clarification! I just installed the playground to see if I can make sense of all of this and how the `treesitter` tree relates to the actual highlighting. I don't quite understand why nothing is highlighted when I'm inside the body of the for loop, but it is (wrongly) highlighted when the cursor is inside the function body that contains the for loop.

**Comment by lukas-reineke** [comment]
> I don't quite understand why nothing is highlighted when I'm inside the body of the for loop

That nothing is highlighted when the cursor is inside the for loop should be fixed now. This was because it found a context closer to the for loop.

> but it is (wrongly) highlighted when the cursor is inside the function body that contains the for loop.

It is not the for loop that is highlighted in this case. It is the whole function body. It is just not as clear as you have trailing indents on blanklines turned off.
This is how it would look like with.

![Screen Capture_select-area_20210402175839](https://user-images.githubusercontent.com/12900252/113400905-86968900-93dd-11eb-97e0-378a2a4e49a5.png)

**Comment by zacmar** [comment]
> > I don't quite understand why nothing is highlighted when I'm inside the body of the for loop
> 
> That nothing is highlighted when the cursor is inside the for loop should be fixed now. This was because it found a context closer to the for loop.
> 
Great, thank you! (Although it doesn't look like this is in the remote yet?) 

> > but it is (wrongly) highlighted when the cursor is inside the function body that contains the for loop.
> 
> It is not the for loop that is highlighted in this case. It is the whole function body. It is just not as clear as you have trailing indents on blanklines turned off.
> This is how it would look like with.
> 
> ![Screen Capture_select-area_20210402175839](https://user-images.githubusercontent.com/12900252/113400905-86968900-93dd-11eb-97e0-378a2a4e49a5.png)

Okay, interesting. But clearly this is not wanted behavior? Or a `treesitter` "bug" (/misconfiguration by me)? Consider these examples:
`lua`
![2021-04-02-130816_684x338_scrot](https://user-images.githubusercontent.com/32982619/113410848-a5345a00-93b4-11eb-9428-04939161ba54.png)
`python`
![2021-04-02-130912_682x352_scrot](https://user-images.githubusercontent.com/32982619/113410856-acf3fe80-93b4-11eb-9457-cfd9f4cfbb95.png)

Notice how in `python` the if block is highlighted, whilst it is not in `lua`. Is this because of my settings? The `treesitter` trees look very similar to me.

**Comment by zacmar** [comment]
So this was indeed misconfiguration by me. When removing the 'block' pattern, it is much smoother for `python`. The question is really whether there are some guidelines/standards that the `treesitter` grammar implementers are supposed to follow? Otherwise one idea may be to add a list of patterns for specific filetypes to this repo, that "do what you would expect".

**Comment by lukas-reineke** [comment]
> The question is really whether there are some guidelines/standards that the treesitter grammar implementers are supposed to follow? Otherwise one idea may be to add a list of patterns for specific filetypes to this repo, that "do what you would expect"

Yes I would like to have good documentation about the different node types. I am still experimenting with this myself. There is some discussion about this in #61 too.
They are different for each filetype and treesitter already has support for over 30 languages. So it's not an easy task.

**Comment by zacmar** [comment]
Okay, sounds good. In my opinion, plugins like this one should offload as much work as possible to `treesitter`, because most things simply come 'for free' then. So as much work as possible should go towards `treesitter` compatibility. As far as I am concerned, this issue can be closed (although it seems as some more broadly-scoped issue still persists). Thank you for the plugin!

**Comment by lukas-reineke** [comment]
Yes I agree. I don't want to build any custom context logic here. Treesitter should handle this.

I'll close this issue, but feel free to comment on #61 if you have recommendations for patterns.
